### ISSUE TITLE
Unable to run pie serve / Document config.json

### ISSUE THREAD

**Issue by jmealo** [PieLabs/pie-cli#102]
On a fresh git clone (or `npm install -g`).

I cannot get `pie serve` to run. I get some errors about `config.json` and `log-config`.

I also get some errors with `../lib/*` not existing when running directly from `./bin/`.

Did I miss something as far as configuration goes?

Thanks,
Jeff

**Environment:**
- node @ `v6.10.0`
- npm @ `3.10.10`
- OSX @ `10.11.5`

**Comment by evaneus** [comment]
Hi Jeff,

Can you capture and attach the output from the command you are running?

Are you following this example or working with different json/html? https://pielabs.github.io/pie-docs/using/quick-start.html

**Comment by jmealo** [comment]
@evaneus I was using the information from README. I'll start over using the quick start guide, if that works I'll close the ticket or change it to include a link from the README.

**Comment by edeustace** [comment]
closing this for now - let me know if it needs re-opening
