### ISSUE TITLE
Allow controller and configure packages to be 1st class npm packages

### ISSUE THREAD

**Issue by edeustace** [PieLabs/pie-cli#147]
We currently find these packages by looking at `/controller` and `/configure` within the pie. While this is convenient it makes re-using packages difficult (it also creates problems when building/publishing packages in a mono-repo).

Allow a pie to optionally define a dependency as one piece of the pie.

package.json: 

```javascript
{ 
  "name" : "@my-org/my-pie",
  "dependencies" : {
   "@my-org/component" : "1.0.0",
    "@my-org/component-controller" : "1.0.0",
    "@my-org/component-configure" : "1.0.0"
  }
  "pie": {
    "player" : "@my-org/component", // default "."
    "controller" : "@my-org/component-controller", // default "./controller"
    "configure": "@my-org/component-configure" // default "./configure"
  }
}
```
This will allow allow easier re-use and will make package publishing simpler.

**Comment by evaneus** [comment]
Per discussion on slack `player` => `element`

Need to make sure to also update documentation for this.

**Comment by edeustace** [comment]
see: PieLabs/pie-cli-libs/issues/1

**Comment by edeustace** [comment]
* [ ] - set up watch
* [ ] - check hybrid set ups (test in installer)
