### ISSUE TITLE
Generated example html needs some additions for legacy components

### ISSUE THREAD

**Issue by rbokel** [PieLabs/pie-cli#32]
1. For using the legacy comps, i have to initialise a ng-app 
2. Some internal libraries expect to find the 'corespring-player class in their parent nodes 

Below you can find a piece of manually edited html, that looks as expected 
```
<body ng-app="corespring-legacy-components">
    <pie-control-panel></pie-control-panel>
    <pie-player class="corespring-player">
      <corespring-function-entry-ng15 pie-id="1"></corespring-function-entry-ng15>
    </pie-player>
  </body>
</html>
```

**Comment by edeustace** [comment]
@rbokel lets talk about this in the morning, I don't think the legacy components can assume that they live in a global application context. Instead each component should initialise it's own app using `angular.bootstrap`.

**Comment by rbokel** [comment]
Ok, i've implemented it, and it seems to work fine. I think, we can close this.

**Comment by edeustace** [comment]
👍
