### ISSUE TITLE
Rename controllers.js to pie-controller.js

### ISSUE THREAD

**Issue by evaneus** [PieLabs/pie-cli#49]
Rename controllers.js to pie-controller.js

This is already reflected in doc, packaging tool should update to implement this in output

**Comment by edeustace** [comment]
@evaneus - before I start on this, I'm wondering if I should set up a new issue for the new bundling api that was laid out in: https://github.com/PieLabs/pie-docs/blob/feature/docs-updates/using/rendering-questions.md and https://github.com/PieLabs/pie-docs/blob/edeustace-comments/using/rendering-questions.md .. and the rename of `controllers.js` to `pie-controller.js` will come under that?

**Comment by edeustace** [comment]
See: #54
