### ISSUE TITLE
remove `-question` suffix from pie-cli commands

### ISSUE THREAD

**Issue by evaneus** [PieLabs/pie-cli#51]
item or assessment item would be the more common industry term, but I'd suggest we just modify these command to not have either 'question' or 'item' in it. 

So 

```
pie pack
pie serve
pie clean
```

**Comment by edeustace** [comment]
`pie pack` reads to me as: 'pack a pie', but you're not packing a pie, you're packing a set of pies based on an Item's (question's) config. `pie pack-item`?

**Comment by evaneus** [comment]
item is the general term we are using in the docs, for want of a better one. The concern i have with using this is that this term in general use usually implies just one question. It also is more used in k-12, 3rd level and i believe less so in non educational institution contexts. As such i think it's safer to leave it out entirely.
