### ISSUE TITLE
Possible to show npm output? 

### ISSUE THREAD

**Issue by rbokel** [PieLabs/pie-cli#62]
When we launch a pie-cli build, it makes a long pause seemingly doing nothing. I think that is when it calls npm install. 
Is it possible to route the output of "npm install" to the console, so we can see that something is happening?

**Comment by edeustace** [comment]
For now add `--log-level '{"default" : "info", "npm-dir" : "verbose"}', I think when we look at #36 we can look at improving the cli experience?

**Comment by rbokel** [comment]
Supplying the log-level doesn't seem to help much.

**Comment by edeustace** [comment]
going to look at this as part of #36
