### ISSUE TITLE
`pie clean` should clean demo from PIE root

### ISSUE THREAD

**Issue by benburton** [PieLabs/pie-cli#73]
Currently if you want to clean a demo for a PIE you have to `cd docs/demo` first. It would be nice if this could be handled automatically at the project root so you can `pie clean info` to start with a cleaned PIE

**Comment by edeustace** [comment]
ok - we can add `pie info --clean` to pre-clean, will add `--clean` to both the default and info app.

**Comment by benburton** [comment]
👍
