### ISSUE TITLE
pack-question: packer.js cannot import from sub-folder of npm-package

### ISSUE THREAD

**Issue by rbokel** [PieLabs/pie-cli#8]
I've tried to add the following line to packer.js 

import ScoringProcessorFactory from 'pie-default-scoring-processor/lib/pie-scoring-processor-factory';

but pie pack-question fails with 

error: [element-bundle]    ModuleNotFoundError: Module not found: Error: Cannot resolve module 'pie-default-scoring-processor/lib/pie-scoring-processor-factory' in /home/rbokel/workspace/pie/corespring-multiple-choice-react/docs/demo
    at /home/rbokel/workspace/pie/pie-cli/node_modules/webpack/lib/Compilation.js:229:38

**Comment by edeustace** [comment]
I think we can park this until the new controller logic code gen is setup.

**Comment by edeustace** [comment]
going to close this for now - we can reopen later if needed
